#!/bin/bash
# Set default theme to luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

# LuCI language default: Simplified Chinese when available
uci set luci.main.lang='zh-cn'
uci commit luci

# === netdata 默认全功能 — 2026-05-31 ===
# 25.12 immwrt 包 netdata-1.38.1-r3 只发 netdata.conf.minimal 模板，
# 不发 netdata.conf；而 /etc/init.d/netdata 写死 -c /etc/netdata/netdata.conf，
# 文件不在 → daemon 6 次 crash → procd 放弃 → LuCI 显示空白。
#
# 修法：创建一个最小化但"全功能"的 netdata.conf：只设 LAN 访问白名单，
# 不禁用任何插件（cgroups/apps/python.d/health 全部跑默认 = 启用）。
# N100 8GB 内存跑全功能毫无压力。
if [ ! -f /etc/netdata/netdata.conf ] && [ -f /etc/netdata/netdata.conf.minimal ]; then
  cat > /etc/netdata/netdata.conf <<'NETDATA_EOF'
# Auto-generated by uci-defaults 99-init-settings (immwrt25.12-2wan)
# Permissive default: LAN access allowed, all plugins enabled (defaults).
[global]
	update every = 2
	run as user = root

[web]
	allow connections from = localhost 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
	allow dashboard from = localhost 10.* 192.168.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.*
NETDATA_EOF
fi

exit 0
